services:
  app:
    build: .
    container_name: e-commerce-app
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example